name: 'Docker Tags by SemVer'
description: 'Create Docker tags by Semantic Version'
branding:
  icon: tag
  color: gray-dark
inputs:
  source:
    description: 'ID or name of the source docker image'
    required: true
  target:
    description: 'Name of the target docker image without tag'
    required: true
  semver:
    description: 'Semantic Version to create docker tags'
    required: true
  suffix:
    description: 'Suffix string to add to tag'
    default: ''
  publish:
    description: 'Publish images or not'
runs:
  using: 'node12'
  main: 'dist/index.js'
