name: Node CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache/Restore node_modules
      id: cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-node_modules-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
    - name: Resolve Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        yarn
    - name: Build
      run: |
        yarn build
    - name: Check whether workspace is clean
      run: |
        if [ -z `git status --porcelain` ]; then exit 0; else exit 1; fi


  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache/Restore node_modules
      id: cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-node_modules-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
    - name: Resolve Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        yarn
    - name: test
      run: |
        yarn test
